print("Selamat Datang di Website Pembelajaran Alttera Academy")
print("Silahkan isi biodata peserta kampus merdeka terlebih dahulu")
print("Nama : Irfan Ahmad Asqolani")
print("Domisili : Tangerang")
print("Jenis Kelamin : Laki-Laki")
print("Asal Kampus : Telkom University")